name: Build DLL

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw -y
        shell: cmd

      - name: Build DLL
        run: g++ -shared -o mouse.dll mouse.cpp
        shell: cmd

      - name: Create ZIP
        shell: powershell
        run: Compress-Archive -Path mouse.dll -DestinationPath mouse.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: mouse-dll
          path: mouse.zip
